application: olmcdev
version: 2-8
runtime: go
api_version: go1

handlers:
##  Contact Information Sections
- url: /about
  static_files: static/html/contact/about.html
  upload: static/html/contact/about.html
- url: /contact
  static_files: static/html/contact/contact.html
  upload: static/html/contact/contact.html
- url: /staff
  static_files: static/html/contact/staff.html
  upload: static/html/contact/staff.html
- url: /connectnow
  static_files: static/html/contact/connectnow.html
  upload: static/html/contact/connectnow.html


##  Education Sections
- url: /education
  static_files: static/html/education/education.html
  upload: static/html/education/education.html
- url: /mission
  static_files: static/html/education/mission.html
  upload: static/html/education/mission.html
- url: /edu-calendar
  static_files: static/html/education/calendar.html
  upload: static/html/education/calendar.html
- url: /sacrament
  static_files: static/html/education/sacrament.html
  upload: static/html/education/sacrament.html

##  Worship Sections
- url: /times
  static_files: static/html/worship/times.html
  upload: static/html/worship/times.html
- url: /funerals
  static_files: static/html/worship/funerals.html
  upload: static/html/worship/funerals.html
- url: /newtestament
  static_files: static/html/worship/newtestament.html
  upload: static/html/worship/newtestament.html
- url: /oldtestament
  static_files: static/html/worship/oldtestament.html
  upload: static/html/worship/oldtestament.html
- url: /responsorial
  static_files: static/html/worship/responsorial.html
  upload: static/html/worship/responsorial.html

##  Ministry Sections
- url: /youth
  static_files: static/html/ministry/youth.html
  upload: static/html/ministry/youth.html
- url: /young-adults
  static_files: static/html/ministry/young-adults.html
  upload: static/html/ministry/young-adults.html
- url: /parents
  static_files: static/html/ministry/parents.html
  upload: static/html/ministry/parents.html
- url: /RCIA
  static_files: static/html/ministry/RCIA.html
  upload: static/html/ministry/RCIA.html
- url: /spiritual-direction
  static_files: static/html/ministry/spiritual-direction.html
  upload: static/html/ministry/spiritual-direction.html
##  Ministry Directories
- url: /min-content
  static_dir: static/html/ministry/content


##  Directories
- url: /images
  static_dir: static/images
- url: /scripts
  static_dir: static/scripts
- url: /angular
  static_dir: static/angular
- url: /dist
  static_dir: static/dist
- url: /pdf
  static_dir: static/pdf
- url: /styles
  static_dir: static/styles


- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml
- url: /apple-touch-icon.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png
- url: /.*
  script: _go_app




