application: olmcdev
version: 2-3
runtime: go
api_version: go1

handlers:
- url: /about
  static_files: static/html/about.html
  upload: static/html/about.html
- url: /contact
  static_files: static/html/contact.html
  upload: static/html/contact.html
- url: /education
  static_files: static/html/education.html
  upload: static/html/education.html
- url: /funerals
  static_files: static/html/funerals.html
  upload: static/html/funerals.html
- url: /hymn
  static_files: static/html/hymn.html
  upload: static/html/hymn.html
- url: /newtestament
  static_files: static/html/newtestament.html
  upload: static/html/newtestament.html
- url: /oldtestament
  static_files: static/html/oldtestament.html
  upload: static/html/oldtestament.html
- url: /prayer
  static_files: static/html/prayer.html
  upload: static/html/prayer.html
- url: /responsorial
  static_files: static/html/responsorial.html
  upload: static/html/responsorial.html
- url: /staff
  static_files: static/html/staff.html
  upload: static/html/staff.html
- url: /times
  static_files: static/html/times.html
  upload: static/html/times.html
- url: /images
  static_dir: static/images
- url: /scripts
  static_dir: static/scripts
- url: /angular
  static_dir: static/angular
- url: /dist
  static_dir: static/dist
- url: /pdf
  static_dir: static/pdf
- url: /styles
  static_dir: static/styles
- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml
- url: /apple-touch-icon.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png
- url: /.*
  script: _go_app




