application: olmcdev
version: 2-7
runtime: go
api_version: go1

handlers:
- url: /about
  static_files: static/html/about.html
  upload: static/html/about.html
- url: /contact
  static_files: static/html/contact.html
  upload: static/html/contact.html
- url: /staff
  static_files: static/html/staff.html
  upload: static/html/staff.html
- url: /times
  static_files: static/html/times.html
  upload: static/html/times.html

##  Education Sections
- url: /education
  static_files: static/html/education/education.html
  upload: static/html/education/education.html
- url: /mission
  static_files: static/html/education/mission.html
  upload: static/html/education/mission.html
- url: /information
  static_files: static/html/education/education.html
  upload: static/html/education/education.html
- url: /edu-calendar
  static_files: static/html/education/calendar.html
  upload: static/html/education/calendar.html
- url: /sacrament
  static_files: static/html/education/sacrament.html
  upload: static/html/education/sacrament.html

##  Worship Sections
- url: /funerals
  static_files: static/html/worship/funerals.html
  upload: static/html/worship/funerals.html
- url: /newtestament
  static_files: static/html/worship/newtestament.html
  upload: static/html/worship/newtestament.html
- url: /oldtestament
  static_files: static/html/worship/oldtestament.html
  upload: static/html/worship/oldtestament.html
- url: /responsorial
  static_files: static/html/worship/responsorial.html
  upload: static/html/worship/responsorial.html


##  Directories
- url: /images
  static_dir: static/images
- url: /scripts
  static_dir: static/scripts
- url: /angular
  static_dir: static/angular
- url: /dist
  static_dir: static/dist
- url: /pdf
  static_dir: static/pdf
- url: /styles
  static_dir: static/styles


- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml
- url: /apple-touch-icon.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png
- url: /.*
  script: _go_app




